export const FETCH_FROM_CART_REQUEST = 'FETCH_FROM_CART_REQUEST';
export const FETCH_FROM_CART_SUCCESS = 'FETCH_FROM_CART_SUCCESS';
export const FETCH_FROM_CART_FAILURE = 'FETCH_FROM_CART_FAILURE';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

export const CLEAR_CART = 'CLEAR_CART';