export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAILURE = 'CATEGORY_LIST_FAILURE';

export const CATEGORY_DETAIL_REQUEST = 'CATEGORY_DETAIL_REQUEST';
export const CATEGORY_DETAIL_SUCCESS = 'CATEGORY_DETAIL_SUCCESS';
export const CATEGORY_DETAIL_FAILURE = 'CATEGORY_DETAIL_FAILURE';
