export const ADD_BRAND_REQUEST = 'ADD_BRAND_REQUEST';
export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS';
export const ADD_BRAND_FAILURE = 'ADD_BRAND_FAILURE';

export const FETCH_BRAND_REQUEST = 'FETCH_BRAND_REQUEST';
export const FETCH_BRAND_SUCCESS = 'FETCH_BRAND_SUCCESS';
export const FETCH_BRAND_FAILURE = 'FETCH_BRAND_FAILURE';

export const LIST_BRAND_REQUEST = 'LIST_BRAND_REQUEST';
export const LIST_BRAND_SUCCESS = 'LIST_BRAND_SUCCESS';
export const LIST_BRAND_FAILURE = 'LIST_BRAND_FAILURE';

export const DELETE_BRAND_REQUEST = 'DELETE_BRAND_REQUEST';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAILURE = 'DELETE_BRAND_FAILURE';

export const EDIT_BRAND_REQUEST = 'EDIT_BRAND_REQUEST';
export const EDIT_BRAND_SUCCESS = 'EDIT_BRAND_SUCCESS';
export const EDIT_BRAND_FAILURE = 'EDIT_BRAND_FAILURE';