export const ADD_PRODUCT_ATTRIBUTES_REQUEST = 'ADD_PRODUCT_ATTRIBUTES_REQUEST';
export const ADD_PRODUCT_ATTRIBUTES_SUCCESS = 'ADD_PRODUCT_ATTRIBUTES_SUCCESS';
export const ADD_PRODUCT_ATTRIBUTES_FAILURE = 'ADD_PRODUCT_ATTRIBUTES_FAILURE';

export const FETCH_PRODUCT_ATTRIBUTES_REQUEST = 'FETCH_PRODUCT_ATTRIBUTES_REQUEST';
export const FETCH_PRODUCT_ATTRIBUTES_SUCCESS = 'FETCH_PRODUCT_ATTRIBUTES_SUCCESS';
export const FETCH_PRODUCT_ATTRIBUTES_FAILURE = 'FETCH_PRODUCT_ATTRIBUTES_FAILURE';

export const LIST_PRODUCT_ATTRIBUTES_REQUEST = 'LIST_PRODUCT_ATTRIBUTES_REQUEST';
export const LIST_PRODUCT_ATTRIBUTES_SUCCESS = 'LIST_PRODUCT_ATTRIBUTES_SUCCESS';
export const LIST_PRODUCT_ATTRIBUTES_FAILURE = 'LIST_PRODUCT_ATTRIBUTES_FAILURE';

export const DELETE_PRODUCT_ATTRIBUTES_REQUEST = 'DELETE_PRODUCT_ATTRIBUTES_REQUEST';
export const DELETE_PRODUCT_ATTRIBUTES_SUCCESS = 'DELETE_PRODUCT_ATTRIBUTES_SUCCESS';
export const DELETE_PRODUCT_ATTRIBUTES_FAILURE = 'DELETE_PRODUCT_ATTRIBUTES_FAILURE';

export const EDIT_PRODUCT_ATTRIBUTES_REQUEST = 'EDIT_PRODUCT_ATTRIBUTES_REQUEST';
export const EDIT_PRODUCT_ATTRIBUTES_SUCCESS = 'EDIT_PRODUCT_ATTRIBUTES_SUCCESS';
export const EDIT_PRODUCT_ATTRIBUTES_FAILURE = 'EDIT_PRODUCT_ATTRIBUTES_FAILURE';